### ISSUE TITLE
Handling of HTTP/2 GOAWAY

### ISSUE THREAD

**Issue by gunters63** [fastify/fastify-reply-from#385]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.1.0

### Plugin version

11.0.1

### Node.js version

20

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

not relevant

### Description

This is currently more of a question than a bug report (but maybe it will develop into one). I am currently unsure where and how to handle this problem.

In my setup I have unary and streaming GRPC calls from a web UI to a .Net GRPC service using HTTP/2 which get forwarded by fastify-http-proxy resp. fastify-reply-from. All is well as long as the GRPC service (https://localhost:50052) is continuously  running.

The problem arises when I restart the GRPC service. The web UI is still running and periodically makes simple 'alive" GRPC calls to recover from the disconnect.

The problem is that, as soon as the GRPC service restarted, the plugin then starts to return 500 errors to the client  like these:

````
[15:34:59.224] ERROR (2327476): New streams cannot be created after receiving a GOAWAY
    reqId: "req-3o"
    req: {
      "method": "POST",
      "url": "/grpc/xxxxxxx",
      "host": "x.y.z",
      "remoteAddress": "x.y.z",
      "remotePort": 39016
    }
    res: {
      "statusCode": 500
    }
    err: {
      "type": "Error",
      "message": "New streams cannot be created after receiving a GOAWAY",
      "stack":
          Error [ERR_HTTP2_GOAWAY_SESSION]: New streams cannot be created after receiving a GOAWAY
              at ClientHttp2Session.request (node:internal/http2/core:1757:13)
              at handleHttp2Req (file:///data/asc/application/services/web-server/web-server.mjs:131842:33)
              at run (file:///data/asc/application/services/web-server/web-server.mjs:132189:11)
              at requestRetry (file:///data/asc/application/services/web-server/web-server.mjs:132201:9)
              at _Reply.from (file:///data/asc/application/services/web-server/web-server.mjs:132101:9)
              at Object.handler (file:///data/asc/application/services/web-server/web-server.mjs:136122:15)
              at preHandlerCallbackInner (file:///data/asc/application/services/web-server/web-server.mjs:14086:28)
              at preHandlerCallback (file:///data/asc/application/services/web-server/web-server.mjs:14058:9)
              at next (file:///data/asc/application/services/web-server/web-server.mjs:13127:13)
              at handleResolve (file:///data/asc/application/services/web-server/web-server.mjs:13142:11)
      "code": "ERR_HTTP2_GOAWAY_SESSION"
    }
````

The top of the stack trace is in the function handleHttp2Req of the plugin (request.js, line 205).

Can someone give me hint if resp. what I can do to recover from this error?

These are my plugin settings:

````
 {
        "disableRequestLogging": true,
        "retryMethods": [],
        "http2": {
          "requestTimeout": 0,
          "sessionTimeout": 0
        },
        "upstream": "https://localhost:50052"
      }
````

### Expected Behavior

No GOAWAY 500 errors happening

(or help how to handle these condition)

**Comment by gunters63** [comment]
I still cannot reproduce that cleanly, sometimes the UI can recover from the error, sometimes not.

I will withdraw the bug report (and maybe come back later) until I know more.

**Comment by gunters63** [comment]
Closing
